@baseUrl = http://localhost:8080/api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQ3ODQxNDcsIm9yaWdfaWF0IjoxNTk0Njk3NzQ3LCJyb2xlSWQiOjMsInNsdWciOiJ0ZXN0dXNlciIsInVzZXJuYW1lIjoidGVzdHVzZXIifQ.SGUlXlMTZ-b0a17tQkwGGeLyvx7on9XncMvkxHQfjU8

###

# @name healthcheck
GET {{baseUrl}}/healthcheck

###

# @name login
POST  {{baseUrl}}/auth/login

{
    "username": "testuser",
    "password": "password"
}

###

# @name SignUp
POST {{baseUrl}}/auth/register

{
	"username": "user02",
	"email": "user02@email.com",
	"firstName": "john",
	"lastName": "doe",
	"password": "123456"
}

###

# @name me

GET  {{baseUrl}}/auth/me
Authorization: Bearer {{token}}
