@baseUrl = http://localhost:8080/api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTMxMDIyMTAsIm9yaWdfaWF0IjoxNTkzMDE1ODEwLCJyb2xlSWQiOjEsInNsdWciOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.53ULdVGm-HeSgMBELGzggZd0GUcGqlBLVPFbDqAp8Kc

###

# @name healthcheck
GET {{baseUrl}}/healthcheck

###

# @name login
POST  {{baseUrl}}/auth/login

{
    "username": "admin",
    "password": "password"
}

###

# @name SignUp
POST {{baseUrl}}/auth/register

{
	"username": "user01",
	"email": "user01@email.com",
	"firstName": "john",
	"lastName": "doe",
	"password": "123456"
}

###

# @name me

GET  {{baseUrl}}/auth/me
Authorization: Bearer {{token}}
