@baseUrl = http://localhost:8080/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTUzMjExOTksIm9yaWdfaWF0IjoxNTk1MjM0Nzk5LCJyb2xlSWQiOjEsInNsdWciOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.AAmnamChETkDsLS33YVUEnv7nZLleGhncgluIWhch-k


###

# @name GetAllReqforms
GET {{baseUrl}}/reqforms
Authorization: Bearer {{token}}

###

# @name UpdateReqform
PUT {{baseUrl}}/reqforms/1
Authorization: Bearer {{token}}

{
    "statusReqform": "verify"
}