@baseUrl = http://localhost:8080/api/v1/spltypes
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTM3NDg0MzksIm9yaWdfaWF0IjoxNTkzNjYyMDM5LCJyb2xlSWQiOjEsInNsdWciOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.smdUryvU8_avmHI5jQHwusyGFPMQ0oR52cB3IWYXEl4

###

# @name GetAllSplTypes
GET {{baseUrl}}
Authorization: Bearer {{token}}

###

# @name GetSplSubTypesBySplTypeID
GET {{baseUrl}}/12/splsubtypes
Authorization: Bearer {{token}}

###

# @name GetSplTypeByID
GET http://localhost:8080/api/v1/spltype/1
Authorization: Bearer {{token}}

###

# @name GetSplSubTypeByID
GET http://localhost:8080/api/v1/splsubtype/1
Authorization: Bearer {{token}}

###