@baseUrl = http://localhost:8080/api/v1/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTMxMDIyMTAsIm9yaWdfaWF0IjoxNTkzMDE1ODEwLCJyb2xlSWQiOjEsInNsdWciOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.53ULdVGm-HeSgMBELGzggZd0GUcGqlBLVPFbDqAp8Kc

###

# @name GetAllUsers
GET {{baseUrl}}/?pageSize=10&page=1
Authorization: Bearer {{token}}

###

# @name GetUserBySlug
GET {{baseUrl}}/staff
Authorization: Bearer {{token}}


###

# @name CreateUser
POST {{baseUrl}}
Authorization: Bearer {{token}}

{
	"username": "user01",
	"email": "user01@email.com",
	"firstName": "john",
	"lastName": "doe",
	"password": "123456",
	"roleId": 3
}

###

# @name UpdateUser
PUT {{baseUrl}}/user01
Authorization: Bearer {{token}}

{
	"status": "I"
}

###

# @name DeleteUser
DELETE  {{baseUrl}}/user01
Authorization: Bearer {{token}}

###

# @name ChangePassword
PUT {{baseUrl}}/fprice/password
Authorization: Bearer {{token}}

{
	"current_password": "12345678",
	"new_password": "password"
}

###

# @name UploadAvatar
PUT  {{baseUrl}}/fprice/avatar
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer {{token}}

--MyBoundary
Content-Disposition: form-data; name="avatar"; filename="golang.png"
Content-Type: image/png

< ../golang.png
--MyBoundary--